auto: true
pygments: true
lsi: false
safe: true

markdown: rdiscount
pygments: true

exclude: ["gh-pages/", "README.md", "Rakefile"]

pca:
  BASE_PATH: http://gongzhitaao.github.com/pcaweb
  ASSET_PATH: false
